name: ToiletUtility
author: TheLittle_Yang
description: A generic Slimefun4-Addon
main: net.toiletmc.toiletutility.ToiletUtility
website: https://github.com/ToiletMC/plugin-ToiletUtility
version: ${project.version}
api-version: 1.21
depend:
  - Slimefun